---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: network
spec:
  releaseName: pihole
  targetNamespace: network
  interval: 1h
  chart:
    spec:
      chart: pihole
      version: 2.17.0
      maxHistory: 3
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  values:
    serviceDns:
      mixedService: true
      type: LoadBalancer
      loadBalancerIP: 192.168.1.222
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
    serviceWeb:
      mixedService: true
      type: LoadBalancer
      loadBalancerIP: 192.168.1.222
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
    serviceDhcp:
      enabled: false
    persistentVolumeClaim:
      enabled: true
    dnsMasq:
      customDnsEntries:
        - address=/pihole.local/192.168.1.222
        - address=/*.pi.local/192.168.1.201
