---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &name uptime-kuma
  namespace: &namespace monitoring
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: docker.io/louislam/uptime-kuma
              tag: latest
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
    service:
      main:
        ports:
          http:
            port: 3001
    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: status.cloud.home
            paths:
              - path: /
                service:
                  name: main
                  port: http
        annotations:
          gethomepage.dev/name: uptime kuma
          gethomepage.dev/description: uptime
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: *namespace
          gethomepage.dev/icon: uptime-kuma.png
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter
            '</head>'
            '<link rel="stylesheet" type="text/css" href="http://themes.cloud.home/css/base/uptime-kuma/plex.css">
            </head>';
            sub_filter_once on;
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
