---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &name changedetection
spec:
  releaseName: *name
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: changedetection
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: alekc-charts
        namespace: flux-system
  values:
    image:
      tag: 0.45.8.1
    env:
      simple:
        BASE_URL: http://changedetection.cloud.home/
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    ingress:
      enabled: true
      hosts:
        - host: 'changedetection.cloud.home'
          paths:
            - path: /
              pathType: Prefix
      className: nginx
      annotations:
        gethomepage.dev/name: *name
        gethomepage.dev/enabled: 'true'
        gethomepage.dev/group: monitoring
        gethomepage.dev/icon: changedetection-io.png
