---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: buildarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: ds
  dataFrom:
    - extract:
        key: DS
