---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &name buildarr
  namespace: &namespace downloads
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        strategy: Recreate
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: callum027/buildarr
              tag: 0.7
            env:
              RADARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: radarr
                    key: api_key
              SONARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: sonarr
                    key: api_key
              PROWLARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: prowlarr
                    key: api_key
              SABNZBD__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: sabznbd
                    key: api_key
              DS__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: ds
                    key: api_key
            command:
              command: ["/bin/sh"]
              args: ["-c", "envsubst < /config-template/buildarr.yaml.tmpl > /config/buildarr.yaml", "/bootstrap.sh"]
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
    persistence:
      config:
        enabled: true
        type: emptyDir
        size: 1Gi
      config-template:
        type: configMap
        name: buildarr-configmap
        globalMounts:
          - path: /config-template/buildarr.yaml.tmpl
            subPath: buildarr.yaml.tmpl
            readOnly: true
    service:
      enabled: false
    probes:
      startup:
        enabled: false
      readiness:
        enabled: false
      liveness:
        enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 128M
      limits:
        cpu: 20m
        memory: 256M
