---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
configMapGenerator:
  - name: buildarr-configmap
    files:
      - buildarr.yaml.tmpl=./config/buildarr.yaml.tmpl
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
