---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    # Doesnt appear to properly support retaining line breaks in yaml files
    # - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    #   rev: 0.2.3
    #   hooks:
    #     - id: yamlfmt
    #       args: [--mapping, "2", --sequence, "4", --offset, "2"]
    rev: v1.5.4
    hooks:
      - id: remove-tabs

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.6
    hooks:
      - id: terraform_fmt

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
