---
# https://taskfile.dev

version: '3'

tasks:
  default:
    silent: true
    cmds:
      - task -l

  brew:
    desc: Install local dependencies with brew
    cmds:
      - brew bundle --file Brewfile --no-lock

  ping:
    desc: check node online status
    cmds:
      - ansible all -i ansible/inventory/hosts --one-line -m 'ping'

  provision:
    desc: Provision cluster with ansible
    dir: ansible
    cmds:
      - ansible-playbook playbooks/setup.yaml

  bootstrap:
    desc: Bootstrap flux
    dir: kubernetes
    cmds:
      - kubectl apply --kustomize bootstrap/kustomization.yaml
      - sops --decrypt ./bootstrap/sops-age.sops.yaml | kubectl apply -f -
      - kubectl apply --kustomize flux/config

  kubeconfig:
    desc: Fetch kubeconfig from controller
    vars:
      MASTER_USERNAME: '{{.MASTER_USERNAME | default "root"}}'
      MASTER_HOST: '{{.MASTER_HOST | default "192.168.1.41"}}'
      KUBERNETES_API: '{{.KUBERNETES_API | default "192.168.1.41"}}'
    cmds:
      - scp {{.MASTER_USERNAME}}@{{.MASTER_HOST}}:/etc/rancher/k3s/k3s.yaml "${KUBECONFIG}"
      - sed -i '' 's/127.0.0.1/{{.KUBERNETES_API}}/g' "${KUBECONFIG}"
      - chmod go-r "${KUBECONFIG}"
