---
# https://taskfile.dev

version: '3'

tasks:
  default:
    silent: true
    cmds:
      - task -l

  brew:
    desc: Install local dependencies with brew
    cmds:
      - brew bundle --file Brewfile --no-lock

includes:
  cluster: ./.taskfiles/cluster/Tasks.yaml
  nas: ./.taskfiles/nas/Tasks.yaml
  tf: ./.taskfiles/terraform/Tasks.yaml
