---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: games
spec:
  chart:
    spec:
      chart: minecraft
      version: '4.9.1'
      sourceRef:
        kind: HelmRepository
        name: minecraft
        namespace: flux-system
  interval: 30m0s
  values:
    resources:
      requests:
        memory: 1Gb
        cpu: 1500m
    minecraftServer:
      eula: 'TRUE'
      difficulty: easy
      maxPlayers: 4
      maxWorldSize: 1000
      spawnProtection: 0
      serviceType: LoadBalancer
    persistence:
      storageClass: longhorn
      dataDir:
        enabled: true
        Size: 5Gi

