---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-pihole
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/network/pihole/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
  dependsOn:
    - name: app-metallb
