---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-jellyseerr
  namespace: flux-system
spec:
  targetNamespace: media
  interval: 10m
  path: ./kubernetes/apps/media/jellyseerr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
  dependsOn:
    - name: app-external-secrets-operator
    - name: app-sonarr
    - name: app-radarr
