---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-metallb
  namespace: metallb-system
spec:
  interval: 10m
  path: "./kubernetes/apps/metallb-ystem/metallb/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
