---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  releaseName: snapshot-controller
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: snapshot-controller
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
  values:
