---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-sabnzbd
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/downloads/sabnzbd/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
  dependsOn:
    - name: app-longhorn
    - name: app-external-secrets-operator
