---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-homepage
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  interval: 10m
  path: ./kubernetes/apps/selfhosted/homepage/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: not-used
        spec:
          template:
            spec:
              containers:
              - name: homepage
                env:
                  - name: HOMEPAGE_VAR_SONARR_API_KEY
                    valueFrom:
                      secretKeyRef:
                        name: sonarr
                        key: api_key
      target:
        kind: Deployment
        name: homepage
