---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-homepage
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  interval: 30m
  path: ./kubernetes/apps/selfhosted/homepage/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
