---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-themepark
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  interval: 10m
  path: ./kubernetes/apps/selfhosted/themepark/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
