---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  releaseName: longhorn
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: longhorn
      version: 1.5.3
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    defaultSettings:
      storageMinimalAvailablePercentage: 5 # 50GB~
    longhornUI:
      replicas: 1
    persistence:
      defaultClassReplicaCount: 2
    ingress:
      enabled: true
      ingressClassName: nginx
      host: lh.cfg.sh
      tls: true
      tlsSecret: ""
      annotations:
        gethomepage.dev/name: longhorn
        gethomepage.dev/description: storage
        gethomepage.dev/enabled: 'true'
        gethomepage.dev/group: management
        gethomepage.dev/icon: longhorn.png
        nginx.ingress.kubernetes.io/auth-url: |-
            http://ak-outpost-authentik-embedded-outpost.security.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
        nginx.ingress.kubernetes.io/auth-signin: |-
          https://lh.cfg.sh/outpost.goauthentik.io/start?rd=$escaped_request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: |-
          Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Host $http_host;
