---
# Putting Longhorn on a sub-path results in a blank page.
# This fixes that by rewriting
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rewrite-longhorn-dashboard
  namespace: longhorn-system
spec:
  replacePathRegex:
    regex: ^/longhorn(/|$)(.*)
    replacement: /$2
