---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &name authentik
spec:
  releaseName: *name
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: authentik
      version: 2023.10.5
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    authentik:
      secret_key:
        valueFrom:
          secretKeyRef:
            name: authentik
            key: secret_key
      env:
        AUTHENTIK_DISABLE_UPDATE_CHECK: 'true'
        AUTHENTIK_REDIS__HOST: redis-authentik.security.svc.cluster.local
        AUTHENTIK_REDIS__PORT: 6379
      envValueFrom:
        AUTHENTIK_POSTGRESQL__HOST:
          valueFrom:
            secretKeyRef:
              name: &secret pg-db-authentik-app
              key: host
        AUTHENTIK_POSTGRESQL__PORT:
          valueFrom:
            secretKeyRef:
              name: *secret
              key: port
        AUTHENTIK_POSTGRESQL__NAME:
          valueFrom:
            secretKeyRef:
              name: *secret
              key: dbname
        AUTHENTIK_POSTGRESQL__USER:
          valueFrom:
            secretKeyRef:
              name: *secret
              key: username
        AUTHENTIK_POSTGRESQL__PASSWORD:
          valueFrom:
            secretKeyRef:
              name: *secret
              key: password
        AUTHENTIK_REDIS__PASSWORD:
          valueFrom:
            secretKeyRef:
              name: redis-authentik
              key: AUTHENTIK_REDIS_PASSWORD
    ingress:
      enabled: true
      hosts:
        - host: sec.cloud.home
          paths:
            - path: /
              pathType: Prefix
      annotations:
        gethomepage.dev/name: *name
        gethomepage.dev/description: auth
        gethomepage.dev/enabled: 'true'
        gethomepage.dev/group: security
        gethomepage.dev/icon: authentik.png
    prometheus:
      serviceMonitor:
        create: true
