---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-db-authentik
spec:
  instances: 2
  failOverDelay: 30
  storage:
    size: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      memory: 400Mi
  monitoring:
    enablePodMonitor: true
