---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-kured
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps/system/kured/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
