---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &name bazarr
  namespace: &namespace downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      maxHistory: 3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/bazarr
      tag: 1.2.3@sha256:133029981e9a93eeb823f36dbfc6ad0c84fd82648ef013d8a613c538647008bc
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [1001]
    service:
      main:
        ports:
          http:
            port: &port 6767
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: bazarr.cloud.home
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: radarr
                    port: *port
        annotations:
          gethomepage.dev/name: *name
          gethomepage.dev/description: subtitles
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: *namespace
          gethomepage.dev/icon: bazarr.png
    persistence:
      media:
        enabled: true
        type: nfs
        server: 192.168.1.234
        path: /volume1/Media
        mountPath: /data/media
      config:
        enabled: true
        mountPath: /config
        accessMode: ReadWriteOnce
        type: pvc
        size: 1Gi
        storageClass: longhorn
    resources:
      requests:
        cpu: 20m
        memory: 256M
      limits:
        memory: 256M
