---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: descheduler
  namespace: system
spec:
  releaseName: descheduler
  interval: 1h
  maxHistory: 3
  chart:
    spec:
      chart: descheduler
      version: 0.27.1
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
