---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &name prowlarr
  namespace: &namespace downloads
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/prowlarr-develop
      tag: 1.10.4.4088@sha256:08995068e6699d8a307627ee476136be3bf8cd4f966f6a07aab76005055c85b8
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [1001]
    env:
      PROWLARR__URL_BASE: &path /
      PROWLARR__PORT: &port 9696
      PROWLARR__API_KEY:
        valueFrom:
          secretKeyRef:
            name: prowlarr
            key: api_key
      PROWLARR_LOG_LEVEL: trace
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: prowlarr.cloud.home
            paths:
              - path: *path
                pathType: Prefix
        annotations:
          gethomepage.dev/name: *name
          gethomepage.dev/description: indexers
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: *namespace
          gethomepage.dev/icon: prowlarr.png
    persistence:
      config:
        enabled: true
        mountPath: /config
        accessMode: ReadWriteOnce
        type: pvc
        size: 1Gi
        storageClass: longhorn
    resources:
      requests:
        cpu: 20m
        memory: 128M
      limits:
        cpu: 40m
        memory: 256M
