---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &name prowlarr
  namespace: &namespace downloads
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        strategy: Recreate
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/prowlarr-develop
              tag: 1.11.1.4146@sha256:c7ad70aaf1dae541ec0fdae0a449cbfcab1e2dd31c46e92f758b4006bfef4a53
            env:
              PROWLARR__URL_BASE: &path /
              PROWLARR__PORT: &port 9696
              PROWLARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: prowlarr
                    key: api_key
              PROWLARR_LOG_LEVEL: trace
            probes:
              readiness:
                enabled: true
                spec:
                  initialDelaySeconds: 60
              startup:
                enabled: true
                spec:
                  initialDelaySeconds: 60
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: prowlarr.cloud.home
            paths:
              - path: /
                service:
                  name: main
                  port: http
        annotations:
          gethomepage.dev/name: *name
          gethomepage.dev/description: indexer mgmt
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: *namespace
          gethomepage.dev/icon: prowlarr.png
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter
            '</head>'
            '<link rel="stylesheet" type="text/css" href="http://themes.cloud.home/css/base/prowlarr/plex.css">
            </head>';
            sub_filter_once on;
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
    resources:
      requests:
        cpu: 20m
        memory: 128M
      limits:
        memory: 256M
