---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-traefik
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/kube-system/traefik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
  dependsOn:
    - name: app-metallb
