---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
  namespace: selfhosted
spec:
  releaseName: homepage
  targetNamespace: selfhosted
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  values:
    enableRbac: true
    serviceAccount:
      create: true
    ingress:
      main:
        ingressClassName: nginx
        enabled: true
        hosts:
          - host: &host cloud.home
            paths:
            - path: /
              pathType: Prefix
    config:
      kubernetes:
        mode: cluster
      bookmarks:
        - dev:
          - github:
            - abbr: gh
              href: https://github.com/
        - social:
          - twitter:
            - abbr: twtr
              href: https://twitter.com/
      services:
        - NAS:
            - Portal:
                description: NAS management portal
                href: http://lilnas:8000
            - PiHole:
                description: PiHole management portal
                href: http://lilnas:3001/admin/
            - Portainer:
                description: Portainer management portal
                href: http://lilnas:19943
      widgets:
        - resources:
            backend: kubernetes
            expanded: true
            cpu: true
            memory: true
        - search:
            provider: duckduckgo
            target: _blank
        - kubernetes:
            cluster:
              show: false
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
