---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: homepage
spec:
  releaseName: homepage
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: homepage
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v0.8.4
    enableRbac: true
    serviceAccount:
      create: true
    ingress:
      main:
        ingressClassName: nginx
        enabled: true
        hosts:
          - host: &host home.cfg.sh
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    env:
      HOMEPAGE_VAR_SONARR_API_KEY:
        valueFrom:
          secretKeyRef:
            name: homepage-sonarr
            key: api_key
      HOMEPAGE_VAR_RADARR_API_KEY:
        valueFrom:
          secretKeyRef:
            name: homepage-radarr
            key: api_key
      HOMEPAGE_VAR_READARR_API_KEY:
        valueFrom:
          secretKeyRef:
            name: homepage-readarr
            key: api_key
      HOMEPAGE_VAR_PROWLARR_API_KEY:
        valueFrom:
          secretKeyRef:
            name: homepage-prowlarr
            key: api_key
      HOMEPAGE_VAR_SABNZBD_API_KEY:
        valueFrom:
          secretKeyRef:
            name: homepage-sabnzbd
            key: api_key
      HOMEPAGE_VAR_PIHOLE_API_KEY:
        valueFrom:
          secretKeyRef:
            name: homepage-pihole
            key: api_key
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 200Mi
    config:
      kubernetes:
        mode: cluster
      bookmarks:
        - dev:
            - github:
                - abbr: gh
                  href: https://github.com/
            - hacker news:
                - abbr: hn
                  href: https://news.ycombinator.com/
        - social:
            - twitter:
                - abbr: twtr
                  href: https://twitter.com/
            - reddit:
                - abbr: rdt
                  href: https://reddit.com/
      services:
        - nas:
            - portal:
                description: management
                href: http://lilnas:8000
                icon: asustor.png
            - pi-hole:
                description: dns
                href: http://lilnas:3001/admin/
                icon: pi-hole.png
                widget:
                  type: pihole
                  url: "http://192.168.1.234:3001"
                  key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"
            - portainer:
                description: containers
                href: https://lilnas:19943
                icon: portainer.png
        - media:
            - jellyfin:
                description: streaming
                href: http://lilnas:8096
                icon: jellyfin.png

      widgets:
        - resources:
            backend: kubernetes
            expanded: true
            cpu: true
            memory: true
        - search:
            provider: duckduckgo
            target: _blank
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
            nodes:
              show: false
        - openmeteo:
          timezone: America/Vancouver
          units: metric
          cache: 5
