---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
  namespace: selfhosted
spec:
  releaseName: homepage
  targetNamespace: selfhosted
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: 1.2.0
      maxHistory: 3
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  values:
    enableRbac: true
    serviceAccount:
      create: true
    ingress:
      main:
        ingressClassName: nginx
        enabled: true
        hosts:
          - host: &host cloud.home
            paths:
            - path: /
              pathType: Prefix
    config:
      kubernetes:
        mode: cluster
      bookmarks:
        - dev:
          - github:
            - abbr: gh
              href: https://github.com/
          - hacker news:
            - abbr: hn
              href: https://news.ycombinator.com/

        - social:
          - twitter:
            - abbr: twtr
              href: https://twitter.com/
          - reddit:
            - abbr: rdt
              href: https://reddit.com/
      services:
        - nas:
            - portal:
                description: management
                href: http://lilnas:8000
                icon: asustor.png
            - pi-hole:
                description: dns
                href: http://lilnas:3001/admin/
                icon: pi-hole.png
            - portainer:
                description: containers
                href: http://lilnas:19943
                icon: portainer.png
        - media:
            - jellyfin:
                description: streaming
                href: http://lilnas:8096
                icon: jellyfin.png
      widgets:
        - resources:
            backend: kubernetes
            expanded: true
            cpu: true
            memory: true
        - search:
            provider: duckduckgo
            target: _blank
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
            nodes:
              show: false
