---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: games
spec:
  chart:
    spec:
      chart: minecraft
      version: 4.9.1
      maxHistory: 3
      sourceRef:
        kind: HelmRepository
        name: minecraft
        namespace: flux-system
  interval: 30m0s
  values:
    resources:
      requests:
        memory: 5G
        cpu: 2000m
    minecraftServer:
      memory: 5G
      eula: 'TRUE'
      difficulty: hard
      maxPlayers: 4
      maxWorldSize: 1000
      spawnProtection: 0
      serviceType: LoadBalancer
      servicePort: 25565
    persistence:
      storageClass: longhorn
      dataDir:
        enabled: true
        Size: 20Gi
    readinessProbe:
      initialDelaySeconds: 300
    livenessProbe:
      initialDelaySeconds: 300

