apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sabzbd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets

  target:
    name: sabzbd

  dataFrom:
    - extract:
        key: SABNZBD
