---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &name sabnzbd
  namespace: &namespace downloads
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/sabnzbd
      tag: 4.0.3@sha256:aff676e3c234f7a4493c75813e296c347c02b6e5374acd1858f8244ea44f2b4a
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [1001]
    env:
      SABNZBD__PORT: &port 8080
      SABNZBD__API_KEY:
        valueFrom:
          secretKeyRef:
            name: sabnzbd
            key: api_key
      SABNZBD__NZB_KEY:
        valueFrom:
          secretKeyRef:
            name: sabnzbd
            key: nzb_key
      SABNZBD__HOST_WHITELIST_ENTRIES: >-
        sabnzbd,
        sabnzbd.default,
        sabnzbd.default.svc,
        sabnzbd.default.svc.cluster,
        sabnzbd.default.svc.cluster.local,
        sabnzbd.cloud.home
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: sabnzbd.cloud.home
            paths:
              - path: /
                pathType: Prefix
        annotations:
          gethomepage.dev/name: *name
          gethomepage.dev/description: downloads
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: *namespace
          gethomepage.dev/icon: sabnzbd-alt.png
    persistence:
      media:
        enabled: true
        type: nfs
        server: 192.168.1.234
        path: /volume1/Media
        mountPath: /data/media
      config:
        enabled: true
        mountPath: /config
        accessMode: ReadWriteOnce
        type: pvc
        size: 1Gi
        storageClass: longhorn
      incomplete:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 5m
        memory: 1.5G
      limits:
        memory: 3G
