---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &name sabnzbd
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/sabnzbd
      tag: 4.1.0@sha256:1c1650511f96108e81d677abe8a2e491507caa023fdc5c2bfc99df087634c9f3
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [1001]
    env:
      SABNZBD__PORT: &port 8080
      SABNZBD__API_KEY:
        valueFrom:
          secretKeyRef:
            name: sabnzbd
            key: api_key
      SABNZBD__NZB_KEY:
        valueFrom:
          secretKeyRef:
            name: sabnzbd
            key: nzb_key
      SABNZBD__HOST_WHITELIST_ENTRIES: >-
        sabnzbd, sabnzbd.downloads, sabnzbd.downloads.svc, sabnzbd.downloads.svc.cluster, sabnzbd.downloads.svc.cluster.local, sabnzbd.cfg.sh
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host nzb.cfg.sh
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
        annotations:
          gethomepage.dev/name: *name
          gethomepage.dev/description: downloads
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: downloads
          gethomepage.dev/icon: sabnzbd-alt.png
          nginx.ingress.kubernetes.io/auth-url: |-
            http://ak-outpost-authentik-embedded-outpost.security.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
            https://nzb.cfg.sh/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter
            '</head>'
            '<link rel="stylesheet" type="text/css" href="https://themes.cfg.sh/css/base/sabnzbd/plex.css">
            </head>';
            sub_filter_once on;
    persistence:
      media:
        enabled: true
        type: nfs
        server: 192.168.1.234
        path: /volume1/Media
        mountPath: /data/media
      config:
        enabled: true
        mountPath: /config
        accessMode: ReadWriteOnce
        type: pvc
        size: 1Gi
        storageClass: longhorn
      incomplete:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 1000m
        memory: 3G
      limits:
        memory: 4G
