---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-external-dns
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps/external-dns/external-dns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
  decryption:
    provider: sops
    secretRef:
      name: sops-age
