---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-lldap
  namespace: flux-system
spec:
  targetNamespace: security
  interval: 10m
  path: ./kubernetes/apps/security/lldap/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
  dependsOn:
    - name: app-secret-generator
    - name: app-cloudnative-pg
    - name: app-external-secrets-operator
