---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-generator
  namespace: system
spec:
  releaseName: secrets-generator
  interval: 1h
  maxHistory: 3
  chart:
    spec:
      chart: kubernetes-secrets-generator
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-secrets-generator
        namespace: flux-system
  values:
    image:
      registry: ghcr.io
      repository: belodetek/kubernetes-secret-generator
      tag: 0.0.4
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 150m
        memory: 192Mi

