---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets-operator
  namespace: external-secrets
spec:
  releaseName: external-secrets-operator
  targetNamespace: external-secrets
  interval: 5m
  chart:
    spec:
      chart: external-secrets
      version: 0.9.1
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: true



