apiVersion: v1
kind: Secret
metadata:
    name: doppler-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:gIRMjxrGsoQLewB1MyjYf/ltjmEhQ5QYwNgsZ6PVXIfhSynYQYI+on70SE1340TzFD2nqI/Cmtf7iW+YzNrr/oh3xc7nDwxU,iv:PCL6cBaLp/HjcCjx87SoTnHwcBaSyKcm6FTo7dBYyc8=,tag:F/NFAkAIFABiOIvlhzadgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16fecg9xqa6u2sd95ajr8ljd2eag6fq5mmtatd2wqv75y6h028d8s93u8xf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZWZCZFRhZjlYT1kxdFFQ
            b3NzWjhKYUxHYlBmWmpOSTdjZW16SnRkdUI0CmJoUDdLckQrZTdJTWorVFZKTk5S
            VVdDaEMycS9yYjFIOXpyN3B4WVRwZEEKLS0tIFAwdUFld1ZJa1ExRUxEZWYrampE
            a3FSTlFEUjVtSitISG43cGYyb05Rc1kK8L6VUep46zX0LxwUGBIJ9ywoCllZKZxe
            zK+Vorgcv0M2LU/Bv9tQa7DPgG5e+nvuQR1dapkWLzyRUT64IlxKBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-13T05:20:43Z"
    mac: ENC[AES256_GCM,data:5yRJ1SKE8U15P+pjVL0JUrZCo/hxrj0Z8Lbu7mm1RzNsyDE5EAq2qxQkS4NS2t+XgYh6OqHALam4ix7h0C5/JfwwmwN5hEDIeFwWmVSZI5InBZ3W27lnIMEqK+CJrCFz9Bin/8Q4kcI0KFU/2mljw464TuCaPf6avGd7fKnCkGg=,iv:sWYYtfgolsVbqeVWoVJO4QVHeCtWVCnKgx3F9OO1JIo=,tag:xrr1WM7DQdWU+78LZqHmRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
