---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-db-sonarr
spec:
  instances: 2
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 7d
    barmanObjectStore:
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: 's3://pi-cluster-backup/sonarr'
      endpointURL: 'https://s3.us-east-005.backblazeb2.com'
      s3Credentials:
        accessKeyId:
          name: backblaze-b2
          key: application_key_id
        secretAccessKey:
          name: backblaze-b2
          key: application_key
