---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: cluster-user-auth
  dataFrom:
    - extract:
        key: WEAVE
