apiVersion: v1
kind: Secret
metadata:
  name: cluster-user-auth
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/type: string
    secret-generator.v1.mittwald.de/length: "32"
data:
  username: admin
