apiVersion: v1
data:
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:RY5wZdXVuAvb9X+jyo85nlIHaIUQDZ+0x62Zww==,iv:5PEJGIoTjIzIw3Cju9b81dd7rRPPiXGvK597SSkvkUc=,tag:heEz9k2kw7qsrBcdeK4CzA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: pihole
    namespace: external-dns
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16fecg9xqa6u2sd95ajr8ljd2eag6fq5mmtatd2wqv75y6h028d8s93u8xf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNDB1b3NNSWdJZjJPOG8r
            SE5zekwvcWZmU0xhVjNJMDRaUDlTSWZ2Wms0CnM2cEVTSnB2cVY4UnF1emxUNDJC
            Yy9hUHI0UkpCeUtiTWVYaUdzdlpHWmsKLS0tIEp6cnQ5NVdORDYxZmZ6WUtsNzN2
            KzEvNmZjYWRHZ3hXZXRRNjdKVlNtYWcKGoXJg9q7XTPRyVCFcmZ7mqd63pyUQMc6
            4tXk0wjdBSdX6msGzZ1zrQxjgWwrC8Mhl7XSRLDkiEPx7zEhZV6I6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-21T03:08:37Z"
    mac: ENC[AES256_GCM,data:JeFnxSmohuFeEGChESN166RqChbJMl1J+BDFigeJ5HrEqG7SspcRzTXU3lgkqrj7uBS88Kzyj/vLvXam2mLQuoKt5lQa6IFRQrNUsGYJ2NwFnbGgYjgxHx+M05xicwJlJsTln9QIGzNf1EUdeKRvTSyC7H0Md2DndTn6vPKHtbc=,iv:NPoldQd3Ac8X/dD8Z/7QVX+fbBD9LUn7fPQ6uz3h6G0=,tag:SCQ49sOSa+F+vw4QdKcmcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
