---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: k8tz
spec:
  releaseName: k8tz
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: k8tz
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8tz
        namespace: flux-system
  values:
    namespace: null
    timezone: America/Vancouver
    cronJobTimeZone: true
