---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-recyclarr
  namespace: flux-system
spec:
  targetNamespace: downloads
  interval: 10m
  path: ./kubernetes/apps/downloads/recyclarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
  dependsOn:
    - name: app-external-secrets-operator
    - name: app-sabnzbd
    - name: app-sonarr
    - name: app-radarr
