---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &name radarr
  namespace: &namespace downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      maxHistory: 3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/radarr
      tag: 4.6.4.7568@sha256:d92c1aeb857aab4ed9d3de9fcd880b332b2d1fb5603b8e322ea24400bc393599
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [1001]
    env:
      RADARR__URL_BASE: &path /
      RADARR__PORT: &port 7878
      RADARR__API_KEY:
        valueFrom:
          secretKeyRef:
            name: radarr
            key: api_key
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: radarr.cloud.home
            paths:
              - path: *path
                pathType: Prefix
                backend:
                  service:
                    name: radarr
                    port: *port
        annotations:
          gethomepage.dev/name: *name
          gethomepage.dev/description: movies
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: *namespace
          gethomepage.dev/icon: radarr.png
    persistence:
      media:
        enabled: true
        type: nfs
        server: 192.168.1.234
        path: /volume1/Media
        mountPath: /data/media
      config:
        enabled: true
        mountPath: /config
        accessMode: ReadWriteOnce
        type: pvc
        size: 1Gi
        storageClass: longhorn
    resources:
      requests:
        cpu: 20m
        memory: 256M
      limits:
        memory: 256M
