---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: &namespace monitoring
spec:
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 48.1.1
      maxHistory: 3
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheus:
      ingress:
        enabled: true
        hosts:
          - prometheus.cloud.home
        annotations:
          gethomepage.dev/name: prometheus
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: *namespace
          gethomepage.dev/icon: prometheus.png
    grafana:
      ingress:
        enabled: true
        hosts:
          - grafana.cloud.home
        annotations:
          gethomepage.dev/name: grafana
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: *namespace
          gethomepage.dev/icon: grafana.png
    alertmanager:
      ingress:
        enabled: true
        hosts:
          - alertmanager.cloud.home
        annotations:
          gethomepage.dev/name: alertmanager
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: *namespace
          gethomepage.dev/icon: alertmanager.png
