---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 48.1.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheus:
      ingress:
        enabled: true
        hosts:
          - ''
        paths:
          - /prometheus
    grafana:
      ingress:
        enabled: true
        hosts:
          - ''
        paths:
          - /grafana
    alertmanager:
      ingress:
        enabled: true
        hosts:
          - ''
        paths:
          - /alertmanager
