---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backblaze-b2
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: backblaze-b2
  dataFrom:
    - extract:
        key: B2_BUCKET_CREDENTIALS
