---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.19.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
