---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  releaseName: ingress-nginx
  interval: 1h
  maxHistory: 3
  chart:
    spec:
      chart: ingress-nginx
      version: 4.8.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
    config:
      custom-http-errors: >-
        401,403,404,500,501,502,503
      ingressclassResource:
        default: true
    defaultBackend:
      enabled: true
      name: error-pages
      image:
        registry: ghcr.io
        image: tarampampam/error-pages
        tag: 2.26
      extraEnvs:
        - name: TEMPLATE_NAME
          value: hacker-terminal
        - name: SHOW_DETAILS
          value: 'true'
