---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  releaseName: ingress-nginx
  targetNamespace: kube-system
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: 4.7.1
      maxHistory: 3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
