---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  releaseName: ingress-nginx
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: ingress-nginx
      version: 4.8.4
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      allowSnippetAnnotations: true
      config:
        custom-http-errors: >-
          401,403,404,500,501,502,503
      ingressclassResource:
        default: true
    defaultBackend:
      enabled: true
      name: error-pages
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 2.26
      extraEnvs:
        - name: TEMPLATE_NAME
          value: hacker-terminal
        - name: SHOW_DETAILS
          value: 'true'
