---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-weave-gitops
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/flux-system/weave-gitops/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
