---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-speedtest-tracker
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps/monitoring/speedtest-tracker
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
