---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-external-secrets-operator
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/external-secrets/external-secrets-operator/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
