---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./descheduler/ks.yaml
  - ./kured/ks.yaml
  - ./reloader/ks.yaml
  - ./secrets-generator/ks.yaml
