---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: https://charts.external-secrets.io
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.jetstack.io
