---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-stirling-pdf
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/selfhosted/stirling-pdf/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
