---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-bazarr
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/downloads/bazarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false

