---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr
  namespace: media
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/recyclarr/recyclarr
      tag: 5.1.1
    env:
      RADARR_API_KEY:
        secretKeyRef:
          name: radarr
          key: api_key
      SONARR_API_KEY:
        secretKeyRef:
          name: sonarr
          key: api_key
    service:
      main:
        enabled: false
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        mountPath: /config
        accessMode: ReadWriteOnce
        type: pvc
        size: 1Gi
        storageClass: longhorn
      config-file:
        enabled: true
        type: configMap
        name: recyclarr
        subPath: recyclarr.yml
        mountPath: /config/recyclarr.yml
        readOnly: true
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 200Mi
