---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &name readarr
  namespace: &namespace downloads
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        strategy: Recreate
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/readarr-develop
              tag: 0.3.10.2287
            env:
              READARR__URL_BASE: &path /
              READARR__PORT: &port 8787
              READARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: readarr
                    key: API_KEY
            resources:
              requests:
                cpu: 20m
                memory: 256M
              limits:
                memory: 256M

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: readarr.cloud.home
            paths:
              - path: *path
                service:
                  name: main
                  port: http
        annotations:
          gethomepage.dev/name: *name
          gethomepage.dev/description: ebooks
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: *namespace
          gethomepage.dev/icon: readarr.png

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
      media:
        enabled: true
        type: nfs
        server: 192.168.1.234
        path: /volume1/Media
        mountPath: /data/media
