---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &name readarr
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        strategy: Recreate
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/readarr-develop
              tag: 0.3.13.2338@sha256:bf8a16b7fb4c17499f8de4c0c71a044e140e90d9c00904d751c1a46470a99033
            env:
              READARR__URL_BASE: &path /
              READARR__PORT: &port 8787
              READARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: readarr
                    key: api_key
            resources:
              requests:
                cpu: 20m
                memory: 256M
              limits:
                memory: 1Gi
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: readarr.cloud.home
            paths:
              - path: *path
                service:
                  name: main
                  port: http
        annotations:
          gethomepage.dev/name: *name
          gethomepage.dev/description: ebooks
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: downloads
          gethomepage.dev/icon: readarr.png
          nginx.ingress.kubernetes.io/auth-url: |-
            http://ak-outpost-authentik-embedded-outpost.security.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
            http://readarr.cloud.home/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter
            '</head>'
            '<link rel="stylesheet" type="text/css" href="http://themes.cloud.home/css/base/readarr/plex.css">
            </head>';
            sub_filter_once on;
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
      media:
        enabled: true
        type: nfs
        server: 192.168.1.234
        path: /volume1/Media
        globalMounts:
          - path: /data/media
