---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &name readarr
  namespace: &namespace downloads
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        strategy: Recreate
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/readarr-develop
              tag: 0.3.10.2287@sha256:c8e4418f32af29d42d4c277dd3696a4c5d905965053a937f66c2c3773c973466
            env:
              READARR__URL_BASE: &path /
              READARR__PORT: &port 8787
              READARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: readarr
                    key: api_key
            resources:
              requests:
                cpu: 20m
                memory: 256M
              limits:
                memory: 1Gi
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: readarr.cloud.home
            paths:
              - path: *path
                service:
                  name: main
                  port: http
        annotations:
          gethomepage.dev/name: *name
          gethomepage.dev/description: ebooks
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: *namespace
          gethomepage.dev/icon: readarr.png
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter
            '</head>'
            '<link rel="stylesheet" type="text/css" href="http://themes.cloud.home/css/base/readarr/plex.css">
            </head>';
            sub_filter_once on;
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
      media:
        enabled: true
        type: nfs
        server: 192.168.1.234
        path: /volume1/Media
        mountPath: /data/media
