---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: system
spec:
  releaseName: reloader
  interval: 1h
  maxHistory: 3
  chart:
    spec:
      chart: reloader
      version: 1.0.32
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
  values:
    reloader:
      podMonitor:
        enabled: true
        namespace: monitoring
