---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-cloudnative-pg
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/cnpg-system/cloudnative-pg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
