---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: pihole
  data:
    - secretKey: PIHOLE_PASSWORD
      remoteRef:
        key: PIHOLE_PASSWORD
