---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-ds
spec:
  releaseName: external-dns
  targetNamespace: network
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    serviceMonitor:
      enabled: true
    logLevel: debug
    policy: upsert-only
    registry: noop
    provider: pihole
    sources:
      - ingress
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: "http://192.168.1.234:3001"
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole
            key: EXTERNAL_DNS_PIHOLE_PASSWORD

