---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-descheduler
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps/kube-system/descheduler/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
