---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: volsync
  namespace: volsync-system
spec:
  releaseName: volsync
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: volsync
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/volsync
      tag: 0.8.0@sha256:894d2da4a49ff8b1e589e20e534d96a7a2cff2269f5703d53d9ce75d51396fc9
