---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: volsync
  namespace: volsync-system
spec:
  releaseName: volsync
  interval: 1h
  maxHistory: 3
  chart:
    spec:
      chart: volsync
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
