---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: mealie
  dataFrom:
    - extract:
        key: AUTHENTIK_LDAP_CREDENTIALS
