---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-db-mealie
spec:
  instances: 2
  storage:
    size: 2Gi
  monitoring:
    enablePodMonitor: true
  backup:
    barmanObjectStore:
      destinationPath: "s3://pi-cluster-backup/mealie"
      endpointURL: "https://s3.us-east-005.backblazeb2.com"
      s3Credentials:
        accessKeyId:
          name: backblaze-b2
          key: APPLICATION_KEY_ID
        secretAccessKey:
          name: backblaze-b2
          key: APPLICATION_KEY
