---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: network
spec:
  releaseName: pihole
  interval: 1h
  maxHistory: 3
  chart:
    spec:
      chart: pihole
      version: 2.17.0
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  values:
    serviceDns:
      mixedService: true
      type: LoadBalancer
      loadBalancerIP: 192.168.1.222
    serviceWeb:
      http:
        enabled: true
    serviceDhcp:
      enabled: false
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - pihole.cloud.home
      annotations:
        gethomepage.dev/name: pi-hole
        gethomepage.dev/description: dns
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: network
        gethomepage.dev/icon: pi-hole.png
    persistentVolumeClaim:
      enabled: true
    monitoring:
      podMonitor:
        enabled: true
